### ISSUE TITLE
homebridge_occupancy_type doobeel not compatible

### ISSUE THREAD

**Issue by RodolfoPortugal** [schmittx/homebridge-homeassistant#19]
I tried its doorbell functionality, with a ring, but the button in the home app, it has a home icon, and below it, not compatible, I believe that camera functionality is missing, re-recognize it, I saw puglins that before ios 11 or 10, ran with simple doorbell.

Do you have any idea how to fix this incompatibility?

**Comment by schmittx** [comment]
You're correct, the doorbell service is not fully implemented in the current state and therefore it's not supported in the native Home app.

I've never looked into this really and have no plans to at the moment. You're welcome to fork this repo and give it a go for yourself though!
