### ISSUE TITLE
Failed getting devices: Error: You are not authenticated.

### ISSUE THREAD

**Issue by rjbluejacker** [schmittx/homebridge-homeassistant#21]
I recently changed from a raspberry pi zero to a raspberry pi 4 and despite using the same configs from the old setup I can't get homebridge-homeassistant to work, when enabled it repeatedly shows:

```
[2/8/2020, 12:37:44 AM] [HomeAssistant] Fetching HomeAssistant devices.
[2/8/2020, 12:37:44 AM] [HomeAssistant] Failed getting devices: Error: You are not authenticated. Retrying...
```

and i get a persistent notification in home-assistant telling me there was a failed login attempt. I have verified that the legacy password is the same in both configs but still no joy. the legacy password works fine to log into home-assistant in the browser.

HA: 0.106.0.dev20200207
HB: latest (digest: c4f657cd2c482dcf397b0eb5c30666603d6108e98e06e2553497d8220113def9)
HB-HA: 1.0.2

**Comment by schmittx** [comment]
This project is no longer maintained, I recommend you use the native Home Assistant integration for HomeKit ([link](https://www.home-assistant.io/integrations/homekit/)) as it provides more functionality at this point.
